const SUPABASE_URL = "https://qclghpggnxjpjffhclau.supabase.co";

const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjbGdocGdnbnhqcGpmZmhjbGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MjAzMzIsImV4cCI6MjA4OTQ5NjMzMn0.u4LlL4t0ouMC5dTbxNag1ZUvnwRzPtOjg1gvTJZdQQk";

const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);